# Generated by Django 4.2.3 on 2023-07-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
